services:
  cloudflared:
    image: cloudflare/cloudflared:2026.1.1
    # command: tunnel --url http://caddy
    # command: tunnel --url run //attention ca c'est pour la prod
    command: tunnel --url http://caddy-public:80
    container_name: cloudflared
    user: "1001:1001"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Paris
    # on a ajout√© ca
    networks:
      - public
    restart: unless-stopped

  caddy:
    image: caddy:2.10
    container_name: caddy-public
    ports:
      - "80:80"
    volumes:
      - ./config/caddy-public/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-public/data:/data
      - ./data/caddy-public/config:/config
    networks:
      - public
    restart: unless-stopped

volumes:
  db_data:

networks:
  public:
    external: true
