services:
  cloudflared:
    image: cloudflare/cloudflared:2026.1.1
    # command: tunnel --url http://caddy
    # command: tunnel --url run //attention ca c'est pour la prod
    command: tunnel --url http://caddy-public:80 --protocol http2
    container_name: cloudflared
    user: "1001:1001"
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Paris
    networks:
      - public
    restart: unless-stopped

  caddy:
    image: caddy:2.10
    container_name: caddy-public
    ports:
      - "80:80"
    volumes:
      - ./config/caddy-public/Caddyfile:/etc/caddy/Caddyfile

    networks:
      - public
    restart: unless-stopped

  caddy-private:
    image: caddy:2.10
    container_name: caddy-private
    ports:
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./config/caddy-private/Caddyfile:/etc/caddy/Caddyfile

    networks:
      - private
    restart: unless-stopped

  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/dockge:/app/data
      - ../:/app/stacks
    environment:
      - DOCKGE_STACKS_DIR=/app/stacks
      - DOCKGE_BASE_URL=/dockge
    networks:
      - private

networks:
  public:
    name: public
    external: true
  private:
    name: private
    external: true
  internet:
    name: internet
    external: true
